var mockData = [
  { id: 'smallfrog732',
    firstName: 'fletcher',
    lastName: 'walker',
    photoURL: 'https://randomuser.me/api/portraits/men/64.jpg' },
  { id: 'blackpeacock942',
    firstName: 'charles',
    lastName: 'rose',
    photoURL: 'https://randomuser.me/api/portraits/men/52.jpg' },
  { id: 'whiteladybug324',
    firstName: 'theodore',
    lastName: 'wang',
    photoURL: 'https://randomuser.me/api/portraits/men/73.jpg' },
  { id: 'whitepanda734',
    firstName: 'hanne',
    lastName: 'winkler',
    photoURL: 'https://randomuser.me/api/portraits/women/17.jpg' },
  { id: 'ticklishcat616',
    firstName: 'falco',
    lastName: 'carvalho',
    photoURL: 'https://randomuser.me/api/portraits/men/26.jpg' },
  { id: 'greenladybug834',
    firstName: 'romy',
    lastName: 'henry',
    photoURL: 'https://randomuser.me/api/portraits/women/83.jpg' },
  { id: 'orangeleopard627',
    firstName: 'zackary',
    lastName: 'white',
    photoURL: 'https://randomuser.me/api/portraits/men/68.jpg' },
  { id: 'ticklishwolf937',
    firstName: 'gilbert',
    lastName: 'edwards',
    photoURL: 'https://randomuser.me/api/portraits/men/2.jpg' },
  { id: 'silverlion685',
    firstName: 'bastien',
    lastName: 'barbier',
    photoURL: 'https://randomuser.me/api/portraits/men/53.jpg' },
  { id: 'bigduck845',
    firstName: 'magdalena',
    lastName: 'bravo',
    photoURL: 'https://randomuser.me/api/portraits/women/80.jpg' },
  ]

export default mockData;

